### ISSUE TITLE
Add minimal backend

### ISSUE THREAD

**Issue by luschnat-ziegler** [luschnat-ziegler/capstone-project#1]
## Value Statement
As a developer - i would like to access country data from an API so i can visualize them in the react app

## Description
Country data has to be available per country (id) as well as bulk as JSON files from endpoints

## Acceptance Criteria
- [x] If existing id in url: Data of 1 country by id
- [x] If invalid id in url: Error code 
- [x] If no id in url: Data of all countries
- [x] Typo in url: Error code

## Tasks
- [x] Set up back-end skeleton
- [x] Set up data model and db via entities
- [x] Controller logic
- [x] Prepare data and import into database
- [x] Test endpoints

## Size
Medium
