### ISSUE TITLE
User Customization

### ISSUE THREAD

**Issue by luschnat-ziegler** [luschnat-ziegler/capstone-project#10]
### Value Statement:

As a developer i would like the back-end to provide an endpoint for user customization (weight preferences for the six categories) so i can implement the respective features in my react app.

### Description:

The future users should be able to update their categorical priorieties (weightEnvironment etc.) so they can later see customized results.

### Acceptance Criteria

User update endpoint:

- [x] checks for logged in user
- [x] accepts json object with weight preferences
- [x] updates user entry in db with new preferences

### Tasks

- [x] Add weight fields to User Entity
- [x] Add routes to UserController (update)

### Complexity

Low
