### ISSUE TITLE
Comment endpoint

### ISSUE THREAD

**Issue by luschnat-ziegler** [luschnat-ziegler/capstone-project#11]
### Value Statement:

As a developer i would like the back-end to provide an endpoint for comments so i can implement a comment feature (for countries).

### Description:

The future users should be able to write and read comments on countries.

### Acceptance Criteria

Comment endpoint (post):

- [x] checks for logged in user
- [x] accepts json with comment data
- [x] saves comment to db

Comment endpoint (get):

- [x] accepts request for all comments on one country (country id)
- [x] returns json with all comments
- [x] or returns error in case of wrong id

### Tasks

- [x] Add Entity for comments (relations to user and country)
- [x] Write controller for comments

### Complexity

Low
