### ISSUE TITLE
Registration + Login Frontend

### ISSUE THREAD

**Issue by luschnat-ziegler** [luschnat-ziegler/capstone-project#12]
### Value Statement:

As a user i would like to register an account and log in in order to customize my preferences (category weights).

### Description:

![RegistrationAndLogin](https://user-images.githubusercontent.com/56539663/100849975-6b455c80-3483-11eb-9358-ab6fa958f592.png)

### Acceptance Criteria

User page:

- [x] when not logged in provides buttons with options for logging in or registering an account
  - [x] register button leads to registration form
  - [x] registration form accepts user data, checks completeness and, when submitted, either returns success or failure (email in use)
  - [x] log in button leads to login page
  - [x] login page accepts mail and pw
  - [x] login page on submit either rejects login (credentials wrong/not in db) or stores returned in local storage
- [x] when logged in shows profile page with two tabs
  - [x] User data tab shows general of logged in user data (names)
  - [x] Preferences tab shows inputs for weights (stepped range sliders)
  - [x] On submit saves data

### Tasks

- [x] Add components for user page
- [x] Add menu with link to user page
- [x] Add Routing to App and implement Routes to Home and User Page

### Complexity

Medium
