### ISSUE TITLE
User Score on home (comparison) page

### ISSUE THREAD

**Issue by luschnat-ziegler** [luschnat-ziegler/capstone-project#14]
### Value Statement:

As a user, when logged in and having customized my weight settings, i would like to access the homepage and see my custom score in order to experience individualized interaction with the app.

### Description:

![customization](https://user-images.githubusercontent.com/56539663/101277287-af9e6880-37b3-11eb-8ce1-1cf0be167ee5.png)

### Acceptance Criteria

Home Page:

- [x] when not logged in, shows no custom score
- [x] when logged in without customization (or equal custom weights), shows no custom score
  - [x] when logged in with custom settings, shows custom score on top of chart

### Tasks

- [x] Write function for score arithmetics
- [x] Include user data fetching and processing in App
- [x] Include user score in Home Component (conditional rendering)
- [x] Lift state for user status change from UserPage to App Component

### Complexity

Medium
