### ISSUE TITLE
Implement proper serializer implementation in BE

### ISSUE THREAD

**Issue by luschnat-ziegler** [luschnat-ziegler/capstone-project#18]
### Value Statement

As a developer i would like to see a proper implementation of Symfony's SerializerInterface instead of custom serializers so i can work with more modular, versatile and cleaner code.

### Description

The controllers make use of custom serializers which works but is clearly a stopgap measure. They should be replaced by Symfony's own components.

### Acceptance Criteria

- [x] Custom serializer not used in CountryController
- [x] Custom serializer not used in UserController
- [x] Custom Serializer not used in TokenController
- [x] Custom Serializer not used in CommentController
- [x] All endpoints still deliver equivalent payload
- [x] Password is no longer submitted by usercontroller
- [x] Custom Serializers deleted

### Tasks

- [x] Research proper serializer and normalizer usage
- [x] Restructure and test controllers
- [x] Clean up backend

### Complexity

Medium
