### ISSUE TITLE
Tests for arithmetic service functions

### ISSUE THREAD

**Issue by luschnat-ziegler** [luschnat-ziegler/capstone-project#19]
### Value Statement:

As a developer i need tests for the calcUserScore and weightedArMEan functions in order to ensure their functionality.

### Description:

Both services do arithmetic calculations based on a number of factors. They have to be tested for all cases

### Acceptance Criteria

weightedArMean

- [ ] No null values: returns simple weighted arithmetic mean of input data and weights
- [ ] One or more null values: Returns weighted arithmetic mean of not-null data
- [ ] One or more null values AND user weights Null on all others: returns null

calcUserScore

- [ ] No user logged in: returns data array as is and writes corresponding status object to data array
- [ ] User logged in but no customizations or equal weights: returns data array as is and writes corresponding status object to data array
- [ ] User logged in with relevant customizations: returns data with custom country data array

### Tasks

- [ ] Write test for services/weightedArMean
- [ ] Write test for services/calcUserScore

### Complexity

Low
