### ISSUE TITLE
Fix disappearing countries when switching pages

### ISSUE THREAD

**Issue by luschnat-ziegler** [luschnat-ziegler/capstone-project#27]
### Value Statement

As a user i would like to be able to switch between the user and home pages without disappearing countries and with proper updates so my use experience is greatly enhanced.

### Description

When switching between the home and user pages, the displayed countries in the chart and the dropdown menus disappear.

### Acceptance Criteria

- [ ] Selected countries persist between site switches 
- [ ] Dropdown defaults are in sync
- [ ] User preference changes and login/logout are reflected properly

### Tasks

- [ ] Lift displayedCountries state to app and update it with fetched new data
- [ ] Configure dropdowns for default values from props

### Complexity

Low
