### ISSUE TITLE
Add minimal frontend

### ISSUE THREAD

**Issue by luschnat-ziegler** [luschnat-ziegler/capstone-project#3]
## Value Statement
As a user - i would like to access the home page and have the possibility to pick two countries to compare. When picked, i would like to see plain country data.

## Description:
![preliminaryversion](https://user-images.githubusercontent.com/56539663/99910306-7a8f1200-2ced-11eb-92f7-eaf2deecbda7.png)

## Acceptance Criteria:
- [x] Home URL leads to homepage
- [ ] Site contains two drop-down menus with countries
- [x] Loading and errors while fetching data are handled properly
- [x] Country data is displayed

## Tasks:
- [ ] Set up react app
- [ ] Set up Home Component
- [x] Set up basic styling
- [x] Fetch data on loading
- [x] Conditional rendering depending on fetch status
- [x] Include drop-downs with search feature
- [x] Render data of chosen countries

## Size:
Medium
