### ISSUE TITLE
Use ValidatorInterface

### ISSUE THREAD

**Issue by luschnat-ziegler** [luschnat-ziegler/capstone-project#30]
### Value Statement

As a developer i need to ensure back-end-side validation in order to make sure no invalid data is entered into the db.

### Description

As of now, validation is only implemented in the react app. While this avoids unnecessary API-calls, back end validation is also needed to add an extra layer of robustness.

### Acceptance Criteria

- [ ] Back end validates password length
- [ ] Back end validates email
- [ ] Back end validates weight settings
- [ ] Back end validates user first and last name
- [ ] Back end rejects invalid requests

### Tasks

- [ ] Update User Entity with constraints
- [ ] Update User Controller with invalid data responses
- [ ] Update front end to conform with new API responses

### Complexity

Low
