### ISSUE TITLE
Add visualization to homepage

### ISSUE THREAD

**Issue by luschnat-ziegler** [luschnat-ziegler/capstone-project#4]
## Value Statement
As a user - i would like access the homepage, choose two countries and see the data in a visualized manner (not text form) so i can access the data better.

## Description
![visualization](https://user-images.githubusercontent.com/56539663/99938668-9aafe700-2d68-11eb-9ba3-3c237e29a7ed.png)

## Acceptance criteria
- [ ] Site contains vertically stacked elements with category heading (Freedom, Environment etc.) and symmetrical bar charts
- [x] Elements are re-rendered on input change (drop-downs)

## Tasks
- [x] Create component for comparison categories
- [x] Mount them into the site
- [x] Connect them to the home component's state with country data

## Complexity
Hard
