### ISSUE TITLE
Add working usage of serializer in countriesController

### ISSUE THREAD

**Issue by luschnat-ziegler** [luschnat-ziegler/capstone-project#5]
## Value Statement
As a developer - i would prefer to see the usage of Symfony's serializer instead of the currently implemented detour to JSON via an array so the code will be clean.

## Description

This should work:

```php
            return new JsonResponse(
                 $serializer->serialize($country, 'json'),
                 JsonResponse::HTTP_OK,
                 [],
                 true
             );
```

## Acceptance Criteria
- [x] Serializer properly serialises the countries object without throwing the normalization error
- [x] Usage of an arrays is removed and the code cleaned up

## Tasks
- [x] Research normalization issue and solve it.
- [x] Re-factor code in countriesController.php

## Complexity
Easy
