### ISSUE TITLE
Add Authorization and authentication

### ISSUE THREAD

**Issue by luschnat-ziegler** [luschnat-ziegler/capstone-project#9]
### Value Statement:

As a developer i would like the back-end to provide endpoints for token-based user registration and login so i can implement corresponding features in my react application.

### Description:

The future users should be able to create an account (email, password, firstName, lastName) and login with their credentials (email and password). On login they should receive a token linked to them. With this token users should be able to request data pertinent to their account and according to their settings.

### Acceptance Criteria

Registration endpoint:

- [x] accepts user data (first, last, pw and email)
- [x] checks for existing email adresses in db and rejects corresponding requests
- [x] creates new User in db
- [x] returns the new user's data

Login endpoint:

- [x] accepts user data (mail and pw)
- [x] looks up user in db and rejects in case of no matches
- [x] creates token for user and saves it to db
- [x] returns token value and expiration time

Authentication functionality:

- [x] checks request for token and - in case of its presence - for validity
- [x] returns error in case of rejection
- [x] returns requested data on acceptance

### Tasks

- [x] Create Entities for User and Token (oneToMany)
- [x] Create controller and routes
- [ ] Custom serializer
- [x] Write AuthenticationService

### Complexity

Medium
